services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: web
    name: dashboard
    env: python
    plan: free
    # A requirements.txt file must exist
    buildCommand: pip install -r requirements.txt
    # A src/app.py file must exist and contain `server=app.server`
    startCommand: cd src && python -m grpc_tools.protoc -I./ --python_out=. --grpc_python_out=.
        point_data_v1.proto && gunicorn --chdir src app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
