# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import point_data_v1_pb2 as point__data__v1__pb2


class PointDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPoints = channel.unary_unary(
                '/pointdata.v1.PointDataService/GetPoints',
                request_serializer=point__data__v1__pb2.PeriodRequest.SerializeToString,
                response_deserializer=point__data__v1__pb2.GetPointsReply.FromString,
                )
        self.AddPoints = channel.unary_unary(
                '/pointdata.v1.PointDataService/AddPoints',
                request_serializer=point__data__v1__pb2.AddPointsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class PointDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PointDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoints,
                    request_deserializer=point__data__v1__pb2.PeriodRequest.FromString,
                    response_serializer=point__data__v1__pb2.GetPointsReply.SerializeToString,
            ),
            'AddPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPoints,
                    request_deserializer=point__data__v1__pb2.AddPointsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pointdata.v1.PointDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PointDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pointdata.v1.PointDataService/GetPoints',
            point__data__v1__pb2.PeriodRequest.SerializeToString,
            point__data__v1__pb2.GetPointsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pointdata.v1.PointDataService/AddPoints',
            point__data__v1__pb2.AddPointsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
